name: Build

on:
  push:
    branches:
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git fetch
      - name: Run './build.ps1'
        run: ./build.ps1 --github-token $GITHUB_TOKEN --target Package
        env:	
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/*